### ISSUE TITLE
Is production ready

### ISSUE THREAD

**Issue by coinpennant** [petabridge/akkadotnet-bootstrap#21]
Is this production ready or is just for testing. Your approach doesn't actually need to perform a DNS resolution on startup. Ans special reason why?

**Comment by Aaronontheweb** [comment]
> Is this production ready

We have people using this in production. We aren't in the habit of directing our users to OSS work we produce that isn't intended to be used in production.

> Your approach doesn't actually need to perform a DNS resolution on startup

No, why would we need to perform DNS resolution? The purpose of `get-dockerip.sh` is to programmatically grab the hostname assigned to us by container networking and inject it into HOCON configuration.
