### ISSUE TITLE
ClusterIP not being set

### ISSUE THREAD

**Issue by Greatsamps** [petabridge/akkadotnet-bootstrap#28]
The cluster IP is not being set correctly. Having looked at both the .cs and DockerFile get-dockerip.sh is never actually executed.

**Comment by Aaronontheweb** [comment]
This was a change we made about a month ago - we no longer actually call the `get-dockerip.sh` and instead we make the following call to get the local node's hostname:

https://github.com/petabridge/akkadotnet-bootstrap/blob/4b7129a109004db77e8285ea979dd690eeee4a4c/src/Akka.Bootstrap.Docker/DockerBootstrap.cs#L45

However, you can still override those values via setting those environment variables.

I have a more detailed example of this at-work using Kubernetes here, but we haven't documented it yet: https://github.com/petabridge/Cluster.WebCrawler/blob/dev/yaml

Does this help answer your question?

**Comment by Greatsamps** [comment]
Hey Aaron,

It does, in which case I should change this issue to: Documentation + DockerFile need updating to no longer reference get-dockerip.sh :)

**Comment by Aaronontheweb** [comment]
Working on this @Greatsamps

**Comment by Aaronontheweb** [comment]
Our documentation has been rewritten along with a complete end-to-end sample, including build scripts and `docker-compose` support. Hope this helps @Greatsamps  https://github.com/petabridge/akkadotnet-bootstrap/tree/dev/src/Akka.Bootstrap.Docker - sorry for the trouble!
