### ISSUE TITLE
Fails to build an image on Docker Windows container

### ISSUE THREAD

**Issue by OmniAsetty** [petabridge/akkadotnet-bootstrap#29]
I followed all steps given in readme file of akkadotnet-bootstrap but I am getting an error
Step 1/16 : FROM microsoft/dotnet:2.0-sdk AS build-env
 ---> 331b8f314522
Step 2/16 : WORKDIR /app
 ---> Using cache
 ---> 49f0b8ee57a5
Step 3/16 : ENV CLUSTER_SEEDS "[]"
 ---> Using cache
 ---> b647d400006b
Step 4/16 : ENV CLUSTER_IP ""
 ---> Using cache
 ---> d30a5852fe16
Step 5/16 : ENV CLUSTER_PORT "5011"
 ---> Using cache
 ---> 068d47bdb21d
Step 6/16 : COPY . ./
 ---> Using cache
 ---> 98ed09828702
Step 7/16 : RUN dotnet restore
 ---> Running in dca31f8ea870
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(928,5): warning MSB3202: The project file "C:\AlertProcessorPortal\AlertProcessorPortal.csproj" was not found. [C:\app\MessageGateway.csproj]
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(928,5): warning MSB3202: The project file "C:\DeviceManagerPortal\DeviceManagerPortal.csproj" was not found. [C:\app\MessageGateway.csproj]
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(928,5): warning MSB3202: The project file "C:\ReportPortal\ReportProcessorPortal.csproj" was not found. [C:\app\MessageGateway.csproj]
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(1019,5): warning MSB3202: The project file "C:\AlertProcessorPortal\AlertProcessorPortal.csproj" was not found. [C:\app\MessageGateway.csproj]
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(1019,5): warning MSB3202: The project file "C:\DeviceManagerPortal\DeviceManagerPortal.csproj" was not found. [C:\app\MessageGateway.csproj]
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(1019,5): warning MSB3202: The project file "C:\ReportPortal\ReportProcessorPortal.csproj" was not found. [C:\app\MessageGateway.csproj]
  Restoring packages for C:\app\MessageGateway.csproj...
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\app\MessageGateway.csproj]
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(114,5): error :   An error occurred while sending the request. [C:\app\MessageGateway.csproj]
C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(114,5): error :   The server name or address could not be resolved [C:\app\MessageGateway.csproj]
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; dotnet restore' returned a non-zero code: 1

It fails on step-7. Do you have any solution to this problem?

**Comment by OmniAsetty** [comment]
I got it resolved.

**Comment by Aaronontheweb** [comment]
@OmniAsetty I added an end-to-end example for building Windows images here: https://github.com/petabridge/akkadotnet-bootstrap/tree/dev/src/Akka.Bootstrap.Docker.Sample
