### ISSUE TITLE
The docker guidance is a mess

### ISSUE THREAD

**Issue by pvillads** [petabridge/akkadotnet-bootstrap#30]
The text in the guidance for using Akka.NET in docker is not great. It has broken links, unfinished sentences and an example that is not very good.

Unfinished sentence: The Dockerfile and get-dockerip.sh

In the latter part  you say:
That will create a new docker image you can use. Suppose we called our image foo.
Once our image is created, we can start it via docker run:
PS> docker run -p 5044:5011 -e CLUSTER_SEEDS='akka.tcp://dread@172.17.0.3:4053' --name dread1 dread.collector

Why do you mention that the name is foo if you do not use it in the docker run command?

Instead, please provide an end-to-end example where you create a running simple demo app, possibly with a command line app that talks to an actor in the container.

**Comment by Aaronontheweb** [comment]
@pvillads sorry for that Peter - this is unacceptable and we'll clean it up.

**Comment by Aaronontheweb** [comment]
Step 1 - an end-to-end sample with some scripts. Still need to add `docker-compose` to get a cluster to form: https://github.com/petabridge/akkadotnet-bootstrap/pull/32

**Comment by Aaronontheweb** [comment]
Our documentation has been rewritten along with a complete end-to-end sample, including build scripts and `docker-compose` support. Hope this helps @pvillads https://github.com/petabridge/akkadotnet-bootstrap/tree/dev/src/Akka.Bootstrap.Docker
